### ISSUE TITLE
Report site bugs.

### ISSUE THREAD

**Issue by uurcan7** [qreardedisback/qreardedwashere.cf#4]
[] Before reporting this bug report, I checked if it was caused by my browser.
<-- Write ** x ** in parentheses. -->
Aynı iki kod - Öneri - @import - ufak bir gereksiz kod
<--- Describe the problem in a way that I can understand. --.
meta viewport Kodundan iki tane var - İngilizce kısmına girilmesine rağmen Dil değiştirme kısmının Türkçe değil İngilizce olması - Muhtemelen bilmiyorsun fakat bir sitenin en büyük düşmanı @import kodudur Bu siteyi yavaşlatır çünkü her açılışta bunu oluşturmaya çalışır - smile style color 444
<--- Add an image if available. It will be useful for me to understand this error. --->
https://prnt.sc/119gsl2 - https://prnt.sc/119gtxl - https://prnt.sc/119guxi - https://prnt.sc/119gvk3

Şimdilik benden bu kadar
Siten oldukça hızlı çalışıyor bir sürü kod eksiği var ama uğraşırsan başaracağını düşünüyorum
Kolay gelsin.

**Comment by qreardedwastakennN** [comment]
- [x] **meta viewport** Kodu tüm sayfalarda düzenlendi.
- [x] İngilizce kısmına girildiği zaman dil değiştirme tuşu Türkçe olarak değiştirildi.
- [x] **small style** Kodu kullanılmayan tüm sayfalardan silindi. 

@import Kodu hakkında bir şey yapılana kadar issue açık bırakılacaktır.

Issue sistemindeki yazıların Türkçe hali eklendiğinde daha sağlıklı kullanın. ( başlık kısmında Report site bugs. yazıyor. )

**Comment by uurcan7** [comment]
@import Kodu hakkında sanırım destek olabilirim
@import kodunda gördüğünüz gibi url ve sonrasında ' ' içerisinde bir link oluyor
O linkte ki kodu alın bu muhtemelen css olacaktır
Ve kendi css dosyanıza entegre edin (import kodunda ki url den çıkan css kodunu kendi css dosyanızın en üstüne koymanız yeterli olacaktır.) html dosyası içerisinde stylesheet ile etiketleyin bu sayede her açılışta oluşturmaya çalışmayacak aksine sunucunuzdan kodları alacaktır bu da süreyi büyük ölçüde kısaltabilir.

**Comment by uurcan7** [comment]
Eğer yapamazsanız benimle iletişime geçin tekrardan destek olmaya çalışırım :)

**Comment by uurcan7** [comment]
![image](https://user-images.githubusercontent.com/79050542/114300296-44013a80-9ac8-11eb-9e0c-a97e6a6f6ee6.png)

**Comment by uurcan7** [comment]
Sitenizin kök klasöründe favicon.ico dosyası bulunamıyor ek olarak türkçe ve ingilizce olmak üzere direk favicon kodları bulunmamakta.

**Comment by qreardedwastakennN** [comment]
@import Hakkındaki gelişimler ileri tarihlere ertelendi. Daha sonra düzenlemeler yapılacak.
